name: Testing out Github Actions extension

on:
    push:
        branches: [main]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "This works yay!"